---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: faces
spec:
  interval: 1h
  url: https://github.com/BuoyantIO/faces-demo
  ref:
    branch: main
  ignore: |
    /*
    !/k8s/01-base/*-profile.yaml
    !/k8s/01-base/faces.yaml
    !/k8s/01-base/faces-gui.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: faces
spec:
  targetNamespace: faces
  interval: 10m
  path: "./k8s/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: faces
  images:
    - name: dwflynn/faces-gui
      newTag: 0.5.0
    - name: dwflynn/faces-service
      newTag: 0.5.0
  patches:
    - patch: |
        - op: replace
          path: /spec/template/spec/containers/0/env/1
          value:
            name: ERROR_FRACTION
            value: "75"
      target:
        kind: Deployment
        name: (face|smiley|color)
