apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: faces-gui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: faces-gui
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 99
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: face
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: face
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 99
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: color
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: color
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 99
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smiley
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smiley
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 99
