apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - kustomizeconfig.yaml
resources:
  - linkerd-crds.yaml
  - linkerd-control-plane.yaml
  - linkerd-viz.yaml
  - linkerd-smi.yaml
  - repositories.yaml
  - namespaces.yaml
secretGenerator:
  - name: linkerd-certs
    namespace: linkerd
    files:
      - ca.crt
      - ca.key
      - issuer.crt
      - issuer.key
